apiVersion: v1
kind: Service
metadata:
  name: mongodb-27017
  annotations:
    cloud.google.com/load-balancer-type: "internal"
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  loadBalancerIP: "35.199.71.175"
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: mongodb