apiVersion: v1
kind: Deployment
metadata:
  name: apitweetconfig
  labels:
    app: apitweetconfig
spec:
  template:
    metadata:
      labels:
        app: apitweetconfig
        tier: web
    spec:
      containers:
      - name: apitweetconfig
        image: leosilvabustos/api-tweets-config:v1
        ports:
        - containerPort: 8888